### ISSUE TITLE
Incompatibility plantuml-additionals plugins

### ISSUE THREAD

**Issue by lublasco** [AlphaNodes/additionals#104]
Hi,

we are trying to install [plantuml plugin](https://github.com/dkd/plantuml) but there seems to be an incompatibility with additionals plugin. After installing plantuml and additionals no issue can be accessed.

This is a part of a production.log:

```
Started GET "/redmine/issues/767" for 10.166.198.2 at 2021-06-01 11:04:04 +0200
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"767"}
  Current user: user1 (id=410)
  Rendering issues/show.html.erb within layouts/base
  Rendered issues/_action_menu.html.erb (6.7ms)
  Rendered plugins/redmine_agile/app/views/issues/_issue_story_points.html.erb (1.7ms)
  Rendered plugins/redmine_agile/app/views/issues/_issue_sprint.html.erb (0.2ms)
  Rendered plugins/redmine_agile/app/views/issues/_agile_data_labels.html.erb (2.7ms)
  Rendered plugins/redmine_reporter/app/views/issues/_reports_link.html.erb (0.6ms)
  Rendered plugins/redmine_reporter/app/views/issues/_show_details_bottom.html.erb (0.9ms)
  Rendered plugins/redmine_contacts_helpdesk/app/views/issues/_ticket_data.html.erb (0.2ms)
  Rendered plugins/redmine_products/app/views/products_issues/_products.html.erb (2.4ms)
  Rendered plugins/redmine_reporting/app/views/issues/_reporting_issue_buttom.html.slim (1.6ms)
  Rendered /usr/lib64/ruby/gems/2.5.0/gems/additional_tags-1.0.1/app/views/issues/_tags.html.slim (0.2ms)
  Rendered plugins/redmine_drive/app/views/issue_drive_files/_shared_files.html.erb (1.5ms)
  Rendered plugins/redmine_checklists/app/views/issues/_checklist.html.erb (1.4ms)
  Rendered issue_relations/_form.html.erb (1.6ms)
  Rendered issues/_relations.html.erb (2.5ms)
  Rendered issues/tabs/_history.html.erb (23.2ms)
  Rendered common/_tabs.html.erb (24.3ms)
  Rendered issues/show.html.erb within layouts/base (69.0ms)
Completed 500 Internal Server Error in 200ms (ActiveRecord: 36.9ms)
  
SystemStackError (stack level too deep):
  
app/models/setting.rb:289:in `text_formatting'
app/helpers/application_helper.rb:1680:in `wiki_helper'
plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:12:in `heads_for_wiki_formatter'
plugins/plantuml/lib/plantuml_helper_patch.rb:23:in `heads_for_wiki_formatter_with_redmine_plantuml'
plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:12:in `heads_for_wiki_formatter'
plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:12:in `heads_for_wiki_formatter'
plugins/plantuml/lib/plantuml_helper_patch.rb:23:in `heads_for_wiki_formatter_with_redmine_plantuml'
plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:12:in `heads_for_wiki_formatter'
plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:12:in `heads_for_wiki_formatter'
plugins/plantuml/lib/plantuml_helper_patch.rb:23:in `heads_for_wiki_formatter_with_redmine_plantuml'
plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:12:in `heads_for_wiki_formatter'
plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:12:in `heads_for_wiki_formatter'
plugins/plantuml/lib/plantuml_helper_patch.rb:23:in `heads_for_wiki_formatter_with_redmine_plantuml'
plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:12:in `heads_for_wiki_formatter'
.../...

plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:12:in `heads_for_wiki_formatter'
plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:12:in `heads_for_wiki_formatter'
plugins/plantuml/lib/plantuml_helper_patch.rb:23:in `heads_for_wiki_formatter_with_redmine_plantuml'
plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:12:in `heads_for_wiki_formatter'
plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:12:in `heads_for_wiki_formatter'
plugins/plantuml/lib/plantuml_helper_patch.rb:23:in `heads_for_wiki_formatter_with_redmine_plantuml'
plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:12:in `heads_for_wiki_formatter'
app/views/issues/tabs/_history.html.erb:40:in `_5fe8b5c21a3eca15e51ad92fcd36908d'
app/views/common/_tabs.html.erb:21:in `block in _9d72a470150637a3909e98733230405d'
app/views/common/_tabs.html.erb:20:in `each'
app/views/common/_tabs.html.erb:20:in `_9d72a470150637a3909e98733230405d'
app/helpers/application_helper.rb:439:in `render_tabs'
app/views/issues/show.html.erb:126:in `_db42231396824d12a634ba251bbdcc88'
app/controllers/issues_controller.rb:107:in `block (2 levels) in show'
app/controllers/issues_controller.rb:99:in `show'
plugins/redmine_reporting/lib/redmine_reporting/sweeper.rb:23:in `around'
plugins/redmine_reporting/lib/redmine_reporting/sweeper.rb:23:in `around'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
```

...
Is there a way we could easily fix this incompatibility?
Thanks in advance for your support!

**Comment by alexandermeindl** [comment]
See https://github.com/AlphaNodes/additional_tags/issues/9 or https://www.redmine.org/issues/34743. This is the same problem. A plugin can only use one solution, If another plugin use a different solution for this, it is not compatible.

**Comment by lublasco** [comment]
I see. Thanks a lot for your explanation, Alexander.

**Comment by alexandermeindl** [comment]
It is a issue with similar functionality for macro buttons: https://www.redmine.org/issues/30986. If this feature is released, we can drop this feature in additionals plugins.

**Comment by lublasco** [comment]
Great to know, Alexander.
