### ISSUE TITLE
500 Internal Server Error 

### ISSUE THREAD

**Issue by radist** [AlphaNodes/additionals#105]
```
App 128 output: I, [2021-06-06T04:29:11.960527 #128]  INFO -- : Started HEAD "/" for 127.0.0.1 at 2021-06-06 04:29:11 +0300
App 128 output: I, [2021-06-06T04:29:11.963067 #128]  INFO -- : Processing by WelcomeController#index as HTML
App 128 output: I, [2021-06-06T04:29:12.895693 #128]  INFO -- : = Running shared code for AnonymousUser (#) "Anonymous"
App 128 output: I, [2021-06-06T04:29:12.896299 #128]  INFO -- : = Finished running shared code for AnonymousUser (#) "Anonymous"
App 128 output: I, [2021-06-06T04:29:13.327648 #128]  INFO -- :   Current user: anonymous
App 128 output: I, [2021-06-06T04:29:13.363077 #128]  INFO -- : Completed 500 Internal Server Error in 1400ms (ActiveRecord: 448.9ms)
App 128 output: F, [2021-06-06T04:29:13.364535 #128] FATAL -- :   
App 128 output: F, [2021-06-06T04:29:13.364582 #128] FATAL -- : ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "dashboards" does not exist
App 128 output: LINE 8:                WHERE a.attrelid = '"dashboards"'::regclass
App 128 output:                                           ^
App 128 output: :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
App 128 output:                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
App 128 output:                      c.collname, col_description(a.attrelid, a.attnum) AS comment
App 128 output:                 FROM pg_attribute a
App 128 output:                 LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
App 128 output:                 LEFT JOIN pg_type t ON a.atttypid = t.oid
App 128 output:                 LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
App 128 output:                WHERE a.attrelid = '"dashboards"'::regclass
App 128 output:                  AND a.attnum > 0 AND NOT a.attisdropped
App 128 output:                ORDER BY a.attnum
App 128 output: ):
App 128 output: F, [2021-06-06T04:29:13.364608 #128] FATAL -- :   
App 128 output: F, [2021-06-06T04:29:13.364637 #128] FATAL -- : plugins/additionals/app/models/dashboard.rb:76:in `default'
App 128 output: plugins/additionals/lib/additionals/patches/welcome_controller_patch.rb:35:in `find_dashboard'
App 128 output: lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

**Comment by alexandermeindl** [comment]
Hi @radist 

did you use https://github.com/AlphaNodes/additionals#installation instruction?
