### ISSUE TITLE
Error after installing plugin Redmine crashing

### ISSUE THREAD

**Issue by possebon** [AlphaNodes/additionals#130]
Hi all,

I installed the Additionals plugin on my Redmine 4.2.4 instance without any errors.

I followed the instructions on README repo.

After restarting Apache and trying to access the Redmine, I just got the page:

We're sorry, but something went wrong.
The issue has been logged for investigation. Please try again later.

Error ID:
249676ad
Details:
Web application could not be started by the Phusion Passenger(R) application server.

Please read [the Passenger log file](https://www.phusionpassenger.com/library/admin/log_file/) (search for the Error ID) to find the details of the error.

You can also get a detailed report to appear directly on this page, but for security reasons it is only provided if Phusion Passenger(R) is run with environment set to development and/or with the friendly error pages option set to on.

I enabled PassengerLogLevel to 5 to tackle the error.

This is the information I got on passenger.log

```
App 129846 output: [ D 2022-03-10 15:17:28.3757 129846/T1 age/Spa/SpawnEnvSetupperMain.cpp:743 ]: shellName = 'nologin' detected as supporting '-l': false
App 129846 output: Error: The application encountered the following error: Bundler found conflicting requirements for the Ruby^@ version:
App 129846 output:   In Gemfile:
App 129846 output:     rails (= 5.2.6.2) was resolved to 5.2.6.2, which depends on
App 129846 output:       Ruby^@ (>= 2.2.2)
App 129846 output:
App 129846 output:     globalid (~> 0.4.2) was resolved to 0.4.2, which depends on
App 129846 output:       Ruby^@ (>= 1.9.3)
App 129846 output:
App 129846 output:     rouge (~> 3.26.0) was resolved to 3.26.1, which depends on
App 129846 output:       Ruby^@ (>= 2.0)
App 129846 output:
App 129846 output:     roadie-rails (~> 2.2.0) was resolved to 2.2.0, which depends on
App 129846 output:       Ruby^@ (>= 2.5)
App 129846 output:
App 129846 output:     marcel was resolved to 1.0.2, which depends on
App 129846 output:       Ruby^@ (>= 2.2)
App 129846 output:
App 129846 output:     csv (~> 3.1.1) was resolved to 3.1.9, which depends on
App 129846 output:       Ruby^@ (>= 2.5.0)
App 129846 output:
App 129846 output:     nokogiri (~> 1.11.1) was resolved to 1.11.7, which depends on
App 129846 output:       Ruby^@ (< 3.1.dev, >= 2.5)
App 129846 output:
App 129846 output:     i18n (~> 1.8.2) was resolved to 1.8.11, which depends on
App 129846 output:       Ruby^@ (>= 2.3.0)
App 129846 output:
App 129846 output:     rbpdf (~> 1.20.0) was resolved to 1.20.1, which depends on
App 129846 output:       Ruby^@ (>= 1.8.7)
App 129846 output:
App 129846 output:     rubyzip (~> 2.3.0) was resolved to 2.3.2, which depends on
App 129846 output:       Ruby^@ (>= 2.4)
App 129846 output:
App 129846 output:     rotp was resolved to 6.2.0, which depends on
App 129846 output:       Ruby^@ (>= 2.3)
App 129846 output:
App 129846 output:     net-ldap (~> 0.17.0) was resolved to 0.17.0, which depends on
App 129846 output:       Ruby^@ (>= 2.0.0)
App 129846 output:
App 129846 output:     redcarpet (~> 3.5.1) was resolved to 3.5.1, which depends on
App 129846 output:       Ruby^@ (>= 1.9.2)
App 129846 output:
App 129846 output:     acts_as_list was resolved to 1.0.4, which depends on
App 129846 output:       Ruby^@ (>= 2.4.7)
App 129846 output:
App 129846 output:     redmine_extensions (~> 0.3.9) was resolved to 0.3.11, which depends on
App 129846 output:       Ruby^@ (>= 2.1)
App 129846 output:
App 129846 output:     additionals was resolved to 3.0.4, which depends on
App 129846 output:       Ruby^@ (>= 2.6)
App 129846 output:
App 129846 output:     rails (= 5.2.6.2) was resolved to 5.2.6.2, which depends on
App 129846 output:       activesupport (= 5.2.6.2) was resolved to 5.2.6.2, which depends on
App 129846 output:       activesupport (= 5.2.6.2) was resolved to 5.2.6.2, which depends on
App 129846 output:         minitest (~> 5.1) was resolved to 5.15.0, which depends on
App 129846 output:           Ruby^@ (< 4.0, >= 2.2)
App 129846 output:
App 129846 output:     Ruby^@ (< 2.8.0, >= 2.4.0) (Bundler::VersionConflict)
App 129846 output:     /usr/local/share/gems/gems/bundler-2.3.8/lib/bundler/resolver.rb:57:in `rescue in start'
App 129846 output:     /usr/local/share/gems/gems/bundler-2.3.8/lib/bundler/resolver.rb:44:in `start'
App 129846 output:     /usr/local/share/gems/gems/bundler-2.3.8/lib/bundler/resolver.rb:23:in `resolve'
App 129846 output:     /usr/local/share/gems/gems/bundler-2.3.8/lib/bundler/definition.rb:269:in `resolve'
App 129846 output:     /usr/local/share/gems/gems/bundler-2.3.8/lib/bundler/definition.rb:468:in `materialize'
App 129846 output:     /usr/local/share/gems/gems/bundler-2.3.8/lib/bundler/definition.rb:190:in `specs'
App 129846 output:     /usr/local/share/gems/gems/bundler-2.3.8/lib/bundler/definition.rb:238:in `specs_for'
App 129846 output:     /usr/local/share/gems/gems/bundler-2.3.8/lib/bundler/runtime.rb:18:in `setup'
App 129846 output:     /usr/local/share/gems/gems/bundler-2.3.8/lib/bundler.rb:151:in `setup'
App 129846 output:     /usr/local/share/gems/gems/bundler-2.3.8/lib/bundler/setup.rb:20:in `block in <top (required)>'
App 129846 output:     /usr/local/share/gems/gems/bundler-2.3.8/lib/bundler/ui/shell.rb:136:in `with_level'
App 129846 output:     /usr/local/share/gems/gems/bundler-2.3.8/lib/bundler/ui/shell.rb:88:in `silence'
App 129846 output:     /usr/local/share/gems/gems/bundler-2.3.8/lib/bundler/setup.rb:20:in `<top (required)>'
App 129846 output:     /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
App 129846 output:     /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
App 129846 output:     /usr/local/share/gems/gems/passenger-6.0.12/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:380:in `activate_gem'
App 129846 output:     /usr/local/share/gems/gems/passenger-6.0.12/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:221:in `block in run_load_path_setup_code'
App 129846 output:     /usr/local/share/gems/gems/passenger-6.0.12/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:544:in `running_bundler'
App 129846 output:     /usr/local/share/gems/gems/passenger-6.0.12/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:220:in `run_load_path_setup_code'
App 129846 output:     /usr/local/share/gems/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:91:in `preload_app'
App 129846 output:     /usr/local/share/gems/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 129846 output:     /usr/local/share/gems/gems/passenger-6.0.12/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
App 129846 output:     /usr/local/share/gems/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 129846 output:     /usr/local/share/gems/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 129846 output:     /usr/local/share/gems/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ D 2022-03-10 15:17:29.3187 129596/Tr age/Cor/Spa/Han/Perform.h:1782 ]: [App 129846 journey] Loading state from /tmp/passenger.spawn.XXXXFMYt0B/response
[ D 2022-03-10 15:17:29.3189 129596/Tr age/Cor/Spa/Han/Perform.h:1208 ]: [App 129846 journey] Step SUBPROCESS_BEFORE_FIRST_EXEC: setting state to STEP_PERFORMED
[ D 2022-03-10 15:17:29.3189 129596/Tr age/Cor/Spa/Han/Perform.h:1419 ]: [App 129846 journey] Step SUBPROCESS_BEFORE_FIRST_EXEC: monotonic begin time is "147395.113689"
[ D 2022-03-10 15:17:29.3190 129596/Tr age/Cor/Spa/Han/Perform.h:1441 ]: [App 129846 journey] Step SUBPROCESS_BEFORE_FIRST_EXEC: monotonic end time is "147395.113689"
[ D 2022-03-10 15:17:29.3190 129596/Tr age/Cor/Spa/Han/Perform.h:1208 ]: [App 129846 journey] Step SUBPROCESS_SPAWN_ENV_SETUPPER_BEFORE_SHELL: setting state to STEP_PERFORMED
[ D 2022-03-10 15:17:29.3191 129596/Tr age/Cor/Spa/Han/Perform.h:1419 ]: [App 129846 journey] Step SUBPROCESS_SPAWN_ENV_SETUPPER_BEFORE_SHELL: monotonic begin time is "147395.113689"
[ D 2022-03-10 15:17:29.3191 129596/Tr age/Cor/Spa/Han/Perform.h:1441 ]: [App 129846 journey] Step SUBPROCESS_SPAWN_ENV_SETUPPER_BEFORE_SHELL: monotonic end time is "147395.146689"
[ D 2022-03-10 15:17:29.3191 129596/Tr age/Cor/Spa/Han/Perform.h:1208 ]: [App 129846 journey] Step SUBPROCESS_OS_SHELL: setting state to STEP_NOT_STARTED
[ D 2022-03-10 15:17:29.3192 129596/Tr age/Cor/Spa/Han/Perform.h:1419 ]: [App 129846 journey] Step SUBPROCESS_OS_SHELL: monotonic begin time is "147395.165689"
[ D 2022-03-10 15:17:29.3192 129596/Tr age/Cor/Spa/Han/Perform.h:1441 ]: [App 129846 journey] Step SUBPROCESS_OS_SHELL: monotonic end time is "147395.165689"
[ D 2022-03-10 15:17:29.3192 129596/Tr age/Cor/Spa/Han/Perform.h:1208 ]: [App 129846 journey] Step SUBPROCESS_SPAWN_ENV_SETUPPER_AFTER_SHELL: setting state to STEP_PERFORMED
[ D 2022-03-10 15:17:29.3193 129596/Tr age/Cor/Spa/Han/Perform.h:1419 ]: [App 129846 journey] Step SUBPROCESS_SPAWN_ENV_SETUPPER_AFTER_SHELL: monotonic begin time is "147395.154689"
[ D 2022-03-10 15:17:29.3193 129596/Tr age/Cor/Spa/Han/Perform.h:1441 ]: [App 129846 journey] Step SUBPROCESS_SPAWN_ENV_SETUPPER_AFTER_SHELL: monotonic end time is "147395.170689"
[ D 2022-03-10 15:17:29.3194 129596/Tr age/Cor/Spa/Han/Perform.h:1208 ]: [App 129846 journey] Step SUBPROCESS_EXEC_WRAPPER: setting state to STEP_PERFORMED
[ D 2022-03-10 15:17:29.3194 129596/Tr age/Cor/Spa/Han/Perform.h:1419 ]: [App 129846 journey] Step SUBPROCESS_EXEC_WRAPPER: monotonic begin time is "147395.170689"
[ D 2022-03-10 15:17:29.3195 129596/Tr age/Cor/Spa/Han/Perform.h:1450 ]: [App 129846 journey] Step SUBPROCESS_EXEC_WRAPPER: end time is "1646936248.5159214", monotonic conversion is 147395.286378
[ D 2022-03-10 15:17:29.3195 129596/Tr age/Cor/Spa/Han/Perform.h:1208 ]: [App 129846 journey] Step SUBPROCESS_WRAPPER_PREPARATION: setting state to STEP_PERFORMED
[ D 2022-03-10 15:17:29.3196 129596/Tr age/Cor/Spa/Han/Perform.h:1428 ]: [App 129846 journey] Step SUBPROCESS_WRAPPER_PREPARATION: begin time is "1646936248.516135", monotonic conversion is 147395.286592
[ D 2022-03-10 15:17:29.3196 129596/Tr age/Cor/Spa/Han/Perform.h:1450 ]: [App 129846 journey] Step SUBPROCESS_WRAPPER_PREPARATION: end time is "1646936248.5912857", monotonic conversion is 147395.361741
[ D 2022-03-10 15:17:29.3197 129596/Tr age/Cor/Spa/Han/Perform.h:1208 ]: [App 129846 journey] Step SUBPROCESS_APP_LOAD_OR_EXEC: setting state to STEP_ERRORED
[ D 2022-03-10 15:17:29.3197 129596/Tr age/Cor/Spa/Han/Perform.h:1428 ]: [App 129846 journey] Step SUBPROCESS_APP_LOAD_OR_EXEC: begin time is "1646936248.5914688", monotonic conversion is 147395.361925
[ D 2022-03-10 15:17:29.3198 129596/Tr age/Cor/Spa/Han/Perform.h:1450 ]: [App 129846 journey] Step SUBPROCESS_APP_LOAD_OR_EXEC: end time is "1646936249.2642694", monotonic conversion is 147396.034725
[ D 2022-03-10 15:17:29.3198 129596/Tr age/Cor/Spa/Han/Perform.h:1176 ]: [App 129846 journey] Step SUBPROCESS_LISTEN: state file does not exist
[ E 2022-03-10 15:17:29.3482 129596/Tr age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /opt/redmine: The application encountered the following error: Bundler found conflicting requirements for the Ruby
  Error ID: 249676ad
  Error details saved to: /tmp/passenger-error-KPCAfF.html


```

```
*** LOCAL GEMS ***

actioncable (5.2.6.2, 5.2.0)
actionmailer (5.2.6.2, 5.2.0)
actionpack (5.2.6.2, 5.2.0)
actionpack-xml_parser (2.0.1)
actionview (5.2.6.2, 5.2.0)
activejob (5.2.6.2, 5.2.0)
activemodel (5.2.6.2, 5.2.0)
activemodel-serializers-xml (1.0.2)
activerecord (5.2.6.2, 5.2.0)
activerecord-session_store (2.0.0)
activestorage (5.2.6.2, 5.2.0)
activesupport (5.2.6.2, 5.2.0)
acts_as_list (1.0.4)
addressable (2.8.0)
arel (9.0.0)
bigdecimal (default: 1.4.1)
builder (3.2.4)
bundler (2.3.8, default: 1.17.3)
bundler-unload (1.0.2)
chunky_png (1.4.0)
cmath (default: 1.0.0)
concurrent-ruby (1.1.9)
connection_pool (2.2.5)
crass (1.0.6)
css_parser (1.11.0)
csv (3.1.9, default: 3.0.9)
date (default: 2.0.2)
dbm (default: 1.0.0)
deface (1.8.1)
did_you_mean (1.3.0)
e2mmap (default: 0.1.0)
erubi (1.10.0)
et-orbi (1.2.6)
etc (default: 1.0.1)
executable-hooks (1.6.1)
fcntl (default: 1.0.0)
fiddle (default: 1.0.0)
fileutils (default: 1.1.0)
forwardable (default: 1.2.0)
fugit (1.5.2)
gem-wrappers (1.4.0)
gemoji (3.0.1)
globalid (1.0.0, 0.4.2)
haml (5.2.2)
htmlentities (4.3.4)
i18n (1.10.0, 1.8.11)
io-console (default: 0.4.7)
ipaddr (default: 1.2.2)
irb (default: 1.0.0)
json (default: 2.1.0)
logger (default: 1.3.0)
loofah (2.14.0)
mail (2.7.1)
marcel (1.0.2, 0.3.3)
matrix (default: 0.1.0)
method_source (1.0.0)
mimemagic (0.3.10)
mini_magick (4.11.0)
mini_mime (1.1.2, 1.0.3)
minitest (5.15.0, 5.11.3)
multi_json (1.15.0)
mutex_m (default: 0.1.0)
mysql2 (0.5.3)
net-ldap (0.17.0)
net-telnet (0.2.0)
nio4r (2.5.8)
nokogiri (1.13.3 x86_64-linux, 1.11.7 x86_64-linux)
openssl (default: 2.1.2)
ostruct (default: 0.1.0)
passenger (6.0.12)
polyglot (0.3.5)
power_assert (1.1.3)
prime (default: 0.1.0)
psych (default: 3.1.0)
public_suffix (4.0.6)
raabro (1.4.0)
racc (1.6.0)
rack (2.2.3)
rack-openid (1.4.2)
rack-test (1.1.0)
rails (5.2.6.2, 5.2.0)
rails-dom-testing (2.0.3)
rails-html-sanitizer (1.4.2)
railties (5.2.6.2, 5.2.0)
rainbow (3.1.1)
rake (13.0.6, 12.3.3)
rbpdf (1.20.1)
rbpdf-font (1.19.1)
rdoc (default: 6.1.2.1)
redcarpet (3.5.1)
redis (4.6.0)
redmine_extensions (0.4.3, 0.3.11)
redmine_plugin_kit (1.0.1)
render_async (2.1.11)
request_store (1.5.1)
rexml (3.2.5, default: 3.1.9.1)
roadie (4.0.0)
roadie-rails (2.2.0)
rotp (6.2.0)
rouge (3.26.1)
rqrcode (2.1.1)
rqrcode_core (1.2.0)
rss (0.2.9, default: 0.2.7)
ruby-openid (2.9.2)
rubygems-bundler (1.4.5)
rubyzip (2.3.2)
rvm (1.11.3.9)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
shell (default: 0.7)
sidekiq (6.4.1)
sidekiq-cron (1.2.0)
slim (4.1.0)
slim-rails (3.3.0)
sprockets (4.0.2)
sprockets-rails (3.4.2)
state_machines (0.5.0)
state_machines-activemodel (0.8.0)
state_machines-activerecord (0.5.2)
stringio (default: 0.0.2)
strscan (default: 1.0.0)
sync (default: 0.5.0)
temple (0.8.2)
test-unit (3.2.9)
thor (1.2.1)
thread_safe (0.3.6)
thwait (default: 0.1.0)
tilt (2.0.10)
tracer (default: 0.1.0)
tzinfo (2.0.4, 1.2.9)
webrick (default: 1.4.4)
websocket-driver (0.7.5)
websocket-extensions (0.1.5)
xmlrpc (0.3.0)
zlib (default: 1.0.0)
```

Any ideas to fix that?

Thanks in advance

**Comment by alexandermeindl** [comment]
Hi @possebon,
which Ruby version are you using and what other Redmine plugins are installed?

**Comment by possebon** [comment]
> Hi @possebon, which Ruby version are you using (see https://github.com/AlphaNodes/additionals#requirements) and what other Redmine plugins are installed?

Hi @alexandermeindl thanks for your reply.

Here are the information:

```
# ruby --version
ruby 2.6.9p207 (2021-11-24 revision 67954) [x86_64-linux]
[root@portfoliogp plugins]# rails --version
Rails 5.2.6.2
```

Going to the folder of Redmine I receive this warning

```
root@portfoliogp ~]# cd /opt/redmine/plugins/
RVM used your Gemfile for selecting Ruby, it is all fine - Heroku does that too,
you can ignore these warnings with 'rvm rvmrc warning ignore /opt/redmine/Gemfile'.
To ignore the warning for all files run 'rvm rvmrc warning ignore allGemfiles'.

Unknown ruby interpreter version (do not know how to handle): >=2.4.0,<2.8.0.
````
Other plugins:
```
[root@portfoliogp plugins]# ls -la
total 16
drwxr-xr-x 11 apache apache  245 Mar 11 09:07 .
drwx------ 18 apache apache 4096 Feb 24 14:25 ..
-rw-rw-r--  1 apache apache  250 Jul 15  2019 IMPORTANT.md
-rw-r--r--  1 apache apache   31 Apr 23  2012 README
drwxr-xr-x  9 apache apache  168 Feb 23 22:14 dashboard
drwxr-xr-x  7 apache apache  138 Feb 24 14:28 easy_mindmup
drwxr-xr-x  7 apache apache  138 Feb 24 14:29 easy_wbs
drwxr-xr-x  9 apache apache  282 Feb 23 22:32 redmine_custom_workflows
drwxr-xr-x 11 apache apache 4096 Feb 24 13:47 redmine_dashboard
drwxr-xr-x  9 apache apache  244 Feb 23 22:23 redmine_drawio
drwxr-xr-x  9 apache apache  148 Feb 25 23:17 redmine_indicator
drwxr-xr-x  8 apache apache  209 Apr  8  2021 redmine_risks
drwxr-xr-x  8 apache apache  144 Feb 23 22:39 redmine_tint_issues
```
Thanks for help.

**Comment by alexandermeindl** [comment]
Are you sure, this  ruby version is used by your application server? If yes, you can try it to remove other plugins to exclude a conflict with a plugin.

**Comment by possebon** [comment]
I don't know Ruby well to be honest. I did the installation following a procedure on the internet post. Looking at Apache config, I found that there is something pointing to a different Ruby version:

```
  PassengerRoot /usr/local/share/gems/gems/passenger-6.0.12
  PassengerDefaultRuby /usr/bin/ruby
```

And this is a different version:

```
ruby 2.5.9p229 (2021-04-05 revision 67939) [x86_64-linux]
[root@portfoliogp ~]#
```

The 2.6.9 Ruby version I installed using RVM and the 2.5.9 was installed using the Rocky Linux (CentOS 8) repo.

I tried to uninstall the 2.5.9 and make Redmine run with the 2.6.9 version without success.

**Comment by alexandermeindl** [comment]
Hi @possebon,
did you get the same error message after uninstalling ruby 2.5.9? I am quite sure that the problem is the ruby with your passenger setup. But as I wrote above you can also test, if other plugins cause some compatibility problems (by removing them for testing).

**Comment by alexandermeindl** [comment]
Another idea: if you remove additionals and start your redmine, you see the used ruby version /admin/info. If you see 2.6.9 there, the right ruby is used.
