### ISSUE TITLE
Method missing error after installation

### ISSUE THREAD

**Issue by g-teley** [AlphaNodes/additionals#132]
After installing the additionals plugin under Redmine 5.0.2 I get the error:

```
/usr/local/www/redmine/app/controllers/application_controller.rb:637:in `accept_rss_auth': undefined method accept_atom_auth' for Class:Class (NoMethodError)
from /usr/local/www/redmine/plugins/additionals/app/controllers/dashboards_controller.rb:7:in `<class:DashboardsController>'
````

`bundle install` and `rake redmine:plugins:migrate` ran with no errors.
MySQL is version 5.7 and Ruby is 2.7

**Comment by alexandermeindl** [comment]
Redmine 5.0.2 is not available at the moment.

If you want to use the main branch, please make sure your installation fits the requirements: https://github.com/AlphaNodes/additionals#requirements

**Comment by g-teley** [comment]
My fault, it's version 5.0

**Comment by alexandermeindl** [comment]
Please use the latest version of main, there was a fix 8 hours ago.

**Comment by g-teley** [comment]
"Please use the latest version of main, there was a fix 8 hours ago."

Okay, missed that one.

**Comment by g-teley** [comment]
I'm now on the latest Redmine build and MySQL 8 and the error is still there.
