### ISSUE TITLE
Do not work with redmine5

### ISSUE THREAD

**Issue by Bazulenkov** [AlphaNodes/additionals#136]
I try to update redmine from 4.2.5 to 5.0.0
I have redmine in docker.

docker-compose.yml 
```
version: '3.9'

services:
  postgres:
    image: postgres:14.2-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # env_file:
    #   - ./.env
    environment:
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=redmine'

  redmine:
    image: redmine:5-alpine
    restart: always
    volumes:
      - redmine-files:/usr/src/redmine/files
      - redmine-plugins:/usr/src/redmine/plugins
    ports:
      - 80:3000
    depends_on:
      - postgres
    # env_file:
    #   - ./.env
    environment:
      - 'REDMINE_DB_POSTGRES=postgres'
      - 'REDMINE_DB_DATABASE=redmine'
      - 'REDMINE_DB_PASSWORD=password'

volumes:
  postgres-data:
  redmine-files:
  redmine-plugins:
```
And I get this log from redmine-container:
```
redmine_1   | Your Gemfile lists the gem puma (>= 0) more than once.
redmine_1   | You should probably keep only one of them.
redmine_1   | Remove any duplicate entries and specify the gem only once.
redmine_1   | While it's not a problem now, it could cause errors if you change the version of one of them later.
redmine_1   | The Gemfile's dependencies are satisfied
redmine_1   | W, [2022-05-02T18:06:04.117466 #17]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system.
redmine_1   | W, [2022-05-02T18:06:04.258574 #17]  WARN -- : Creating scope :sorted. Overwriting existing method User.sorted.
redmine_1   | W, [2022-05-02T18:06:04.283363 #17]  WARN -- : Creating scope :visible. Overwriting existing method Principal.visible.
redmine_1   | => Booting Puma
redmine_1   | => Rails 6.1.4.7 application starting in production 
redmine_1   | => Run `bin/rails server --help` for more startup options
redmine_1   | W, [2022-05-02T18:06:10.228852 #1]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system.
redmine_1   | W, [2022-05-02T18:06:10.357435 #1]  WARN -- : Creating scope :sorted. Overwriting existing method User.sorted.
redmine_1   | W, [2022-05-02T18:06:10.376834 #1]  WARN -- : Creating scope :visible. Overwriting existing method Principal.visible.
redmine_1   | W, [2022-05-02T18:06:10.474244 #1]  WARN -- : DEPRECATION WARNING: Application#self.accept_rss_auth is deprecated and will be removed in Redmine 6.0. Please use #self.accept_atom_auth instead. (called from <class:DashboardsController> at /usr/src/redmine/plugins/additionals/app/controllers/dashboards_controller.rb:9)
redmine_1   | Exiting
redmine_1   | /usr/src/redmine/app/controllers/application_controller.rb:637:in `accept_rss_auth': undefined method `accept_atom_auth' for Class:Class (NoMethodError)
redmine_1   | 
redmine_1   |     self.class.accept_atom_auth(*actions)
redmine_1   |               ^^^^^^^^^^^^^^^^^
redmine_1   | 	from /usr/src/redmine/plugins/additionals/app/controllers/dashboards_controller.rb:9:in `<class:DashboardsController>'
redmine_1   | 	from /usr/src/redmine/plugins/additionals/app/controllers/dashboards_controller.rb:3:in `<top (required)>'
redmine_1   | 	from /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
redmine_1   | 	from /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
redmine_1   | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:27:in `require'
redmine_1   | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
redmine_1   | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `cget'
redmine_1   | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:237:in `block (2 levels) in eager_load'
redmine_1   | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
redmine_1   | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
redmine_1   | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `ls'
redmine_1   | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:232:in `block in eager_load'
redmine_1   | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `synchronize'
redmine_1   | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `eager_load'
redmine_1   | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `each'
redmine_1   | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `eager_load_all'
redmine_1   | 	from /usr/local/bundle/gems/railties-6.1.4.7/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
redmine_1   | 	from /usr/local/bundle/gems/railties-6.1.4.7/lib/rails/initializable.rb:32:in `instance_exec'
redmine_1   | 	from /usr/local/bundle/gems/railties-6.1.4.7/lib/rails/initializable.rb:32:in `run'
redmine_1   | 	from /usr/local/bundle/gems/railties-6.1.4.7/lib/rails/initializable.rb:61:in `block in run_initializers'
redmine_1   | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
redmine_1   | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
redmine_1   | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
redmine_1   | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
redmine_1   | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each'
redmine_1   | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `call'
redmine_1   | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
redmine_1   | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
redmine_1   | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
redmine_1   | 	from /usr/local/bundle/gems/railties-6.1.4.7/lib/rails/initializable.rb:60:in `run_initializers'
redmine_1   | 	from /usr/local/bundle/gems/railties-6.1.4.7/lib/rails/application.rb:391:in `initialize!'
redmine_1   | 	from /usr/src/redmine/config/environment.rb:16:in `<top (required)>'
redmine_1   | 	from /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
redmine_1   | 	from /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
redmine_1   | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
redmine_1   | 	from /usr/local/bundle/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `block in require'
redmine_1   | 	from /usr/local/bundle/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:299:in `load_dependency'
redmine_1   | 	from /usr/local/bundle/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `require'
redmine_1   | 	from config.ru:3:in `block in <main>'
redmine_1   | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
redmine_1   | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
redmine_1   | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
redmine_1   | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
redmine_1   | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
redmine_1   | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
redmine_1   | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
redmine_1   | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
redmine_1   | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
redmine_1   | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
redmine_1   | 	from /usr/local/bundle/gems/railties-6.1.4.7/lib/rails/commands/server/server_command.rb:39:in `start'
redmine_1   | 	from /usr/local/bundle/gems/railties-6.1.4.7/lib/rails/commands/server/server_command.rb:144:in `block in perform'
redmine_1   | 	from <internal:kernel>:90:in `tap'
redmine_1   | 	from /usr/local/bundle/gems/railties-6.1.4.7/lib/rails/commands/server/server_command.rb:135:in `perform'
redmine_1   | 	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
redmine_1   | 	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
redmine_1   | 	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
redmine_1   | 	from /usr/local/bundle/gems/railties-6.1.4.7/lib/rails/command/base.rb:69:in `perform'
redmine_1   | 	from /usr/local/bundle/gems/railties-6.1.4.7/lib/rails/command.rb:48:in `invoke'
redmine_1   | 	from /usr/local/bundle/gems/railties-6.1.4.7/lib/rails/commands.rb:18:in `<top (required)>'
redmine_1   | 	from bin/rails:4:in `require'
redmine_1   | 	from bin/rails:4:in `<main>'
redmine-admin5_redmine_1 exited with code 1
```

with redmine:4.2.5-alpine all works!

without plugin "aditionals" with redmine:5.0.0-alpine also all works!

**Comment by alexandermeindl** [comment]
See #135

**Comment by whotopia** [comment]
In my case, the redmine5 version of additionals works, however the tab for managing main menus at /settings/plugin/additionals?tab=menu takes me to the "General" tab.    I cannot add custom menus.  Would anyone know why this might be happening?

**Comment by alexandermeindl** [comment]
> In my case, the redmine5 version of additionals works, however the tab for managing main menus at /settings/plugin/additionals?tab=menu takes me to the "General" tab. I cannot add custom menus. Would anyone know why this might be happening?

This fearure was dropped with upcoming version, see https://github.com/AlphaNodes/additionals/blob/main/CHANGELOG.md

**Comment by whotopia** [comment]
> > In my case, the redmine5 version of additionals works, however the tab for managing main menus at /settings/plugin/additionals?tab=menu takes me to the "General" tab. I cannot add custom menus. Would anyone know why this might be happening?
> 
> This fearure was dropped with upcoming version, see https://github.com/AlphaNodes/additionals/blob/main/CHANGELOG.md


Oh!  That's a real shame.  It's a very useful feature.   Is there some other means to do this via the UI in ver 5, instead of having to patch things?

**Comment by Bazulenkov** [comment]
I close issue. Redmine 5.0.1 with additionals from main branch works fine.

**Comment by Bazulenkov** [comment]
I close issue. Redmine 5.0.1 with additionals from main branch works fine.
