### ISSUE TITLE
[Ruby 2.7] [Redmine 4.2.x] [Additionals 3.0.5.2] Searching for the right redmine_saml version

### ISSUE THREAD

**Issue by danowar2k** [AlphaNodes/additionals#157]
Sorry, but the redmine_saml repository doesn't have the issues tab...

I'm currently using additionals 3.0.5.2 and tried to install redmine_saml 1.0.1 (because the newer 1.0.3 is only Redmine 5.x compatible)

The installation stopped with this output:

```
    rake aborted!
    NoMethodError: undefined method `load_settings' for Additionals:Module
    Did you mean?  setting
    /var/redmine/code/4.2.8/plugins/redmine_saml/init.rb:22:in `block in <top (required)>'
    /var/redmine/code/4.2.8/lib/redmine/plugin.rb:94:in `instance_eval'
    /var/redmine/code/4.2.8/lib/redmine/plugin.rb:94:in `register'
    /var/redmine/code/4.2.8/plugins/redmine_saml/init.rb:7:in `<top (required)>'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
    /var/redmine/code/4.2.8/lib/redmine/plugin.rb:187:in `block in load'
    /var/redmine/code/4.2.8/lib/redmine/plugin.rb:178:in `each'
    /var/redmine/code/4.2.8/lib/redmine/plugin.rb:178:in `load'
    /var/redmine/code/4.2.8/config/initializers/30-redmine.rb:20:in `<top (required)>'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:285:in `load'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:285:in `block in load'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:285:in `load'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/railties-5.2.8.1/lib/rails/engine.rb:663:in `block in load_config_initializer'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/notifications.rb:170:in `instrument'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/railties-5.2.8.1/lib/rails/engine.rb:662:in `load_config_initializer'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/railties-5.2.8.1/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/railties-5.2.8.1/lib/rails/engine.rb:619:in `each'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/railties-5.2.8.1/lib/rails/engine.rb:619:in `block in <class:Engine>'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/railties-5.2.8.1/lib/rails/initializable.rb:32:in `instance_exec'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/railties-5.2.8.1/lib/rails/initializable.rb:32:in `run'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/railties-5.2.8.1/lib/rails/initializable.rb:61:in `block in run_initializers'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/railties-5.2.8.1/lib/rails/initializable.rb:50:in `each'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/railties-5.2.8.1/lib/rails/initializable.rb:50:in `tsort_each_child'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/railties-5.2.8.1/lib/rails/initializable.rb:60:in `run_initializers'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/railties-5.2.8.1/lib/rails/application.rb:361:in `initialize!'
    /var/redmine/code/4.2.8/config/environment.rb:16:in `<top (required)>'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/railties-5.2.8.1/lib/rails/application.rb:337:in `require_environment!'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/railties-5.2.8.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
    /var/redmine/code/4.2.8/.appgems/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
    /var/redmine/code/4.2.8/.appgems/gems/bundler-2.3.23/lib/bundler/cli/exec.rb:58:in `load'
    /var/redmine/code/4.2.8/.appgems/gems/bundler-2.3.23/lib/bundler/cli/exec.rb:58:in `kernel_load'
    /var/redmine/code/4.2.8/.appgems/gems/bundler-2.3.23/lib/bundler/cli/exec.rb:23:in `run'
    /var/redmine/code/4.2.8/.appgems/gems/bundler-2.3.23/lib/bundler/cli.rb:486:in `exec'
    /var/redmine/code/4.2.8/.appgems/gems/bundler-2.3.23/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    /var/redmine/code/4.2.8/.appgems/gems/bundler-2.3.23/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
    /var/redmine/code/4.2.8/.appgems/gems/bundler-2.3.23/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
    /var/redmine/code/4.2.8/.appgems/gems/bundler-2.3.23/lib/bundler/cli.rb:31:in `dispatch'
    /var/redmine/code/4.2.8/.appgems/gems/bundler-2.3.23/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
    /var/redmine/code/4.2.8/.appgems/gems/bundler-2.3.23/lib/bundler/cli.rb:25:in `start'
    /var/redmine/code/4.2.8/.appgems/gems/bundler-2.3.23/exe/bundle:48:in `block in <top (required)>'
    /var/redmine/code/4.2.8/.appgems/gems/bundler-2.3.23/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
    /var/redmine/code/4.2.8/.appgems/gems/bundler-2.3.23/exe/bundle:36:in `<top (required)>'

```

**NoMethodError: undefined method `load_settings' for Additionals:Module**

Am I using the correct additionals version? Or do I have to use another tag or commit?

**Comment by alexandermeindl** [comment]
Hi @danowar2k,

this has a reason we do no allow new issues for plugin redmine_saml: we do not offer support on GitHub for it. We offer commercial support for our on premise customers. To do for more information https://alphanodes.com

**Comment by danowar2k** [comment]
Okay, but maybe you could update the README.md file to explain the Issue tab absence and its reason? (By the way, I couldn't find the plugin on https://alphanodes.com/, am I missing something?

**Comment by alexandermeindl** [comment]
Which plugin?  it is on github. The point is support and consulting. This is time consuming for this topic.

**Comment by danowar2k** [comment]
The plugin I talked about in the first post, redmine_saml. Sorry I'm stressing you, so I'll just stop here.

**Comment by alexandermeindl** [comment]
> The plugin I talked about in the first post, redmine_saml. Sorry I'm stressing you, so I'll just stop here.

Hi, no problem. But why do you search for the plugin on alphanodes.com, it is available as open source at GitHub here?

**Comment by danowar2k** [comment]
Here's my train of thought and what I did:

* I migrated from https://github.com/ixti/redmine_tags to https://github.com/AlphaNodes/additional_tags.
* I then tried to solve an age-old issue by trying to install https://github.com/AlphaNodes/redmine_saml
* I got the error, wanted to open an issue on the github page and discovered the missing tab
* I noticed that both additional_tags and redmine_saml come from the same organization, found the link to https://alphanodes.com/ and visited the site to look for docs for redmine_saml or a way to ask about the error
* I could find both additionals and additional_tags on the page, but didn't see redmine_saml mentioned at all
* I read https://github.com/AlphaNodes/redmine_saml/blob/main/README.md , didn't find anything about commercial support or something
* Github doesn't provide email addresses from repository owners, so I decided to open the installation issue on https://github.com/AlphaNodes/additionals because maybe it's a problem with additionals and not with redmine_saml

If https://github.com/AlphaNodes/redmine_saml/blob/main/README.md would have anything in it like

"We do not offer support for the open source community. If you require support for this plugin, please consider buying a support license, see https://alphanodes.com/pricing"

I would have probably stopped earlier ;-)
