### ISSUE TITLE
CreateDashboardDefaults may fail to migrate if sudo mode enabled

### ISSUE THREAD

**Issue by HighwayStar** [alphanodes/additionals#186]
When redmine configured to use sudo:
 sudo_mode: true 
in config/configuration.yml

CreateDashboardDefaults migration may fail if admin user has admin attribute set to false by sudo timeout.

producing log like this
```
== 4 CreateDashboardRoles: migrated (0.0015s) =================================

== 5 CreateDashboardDefaults: migrating =======================================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `id' for nil:NilClass
/home/tomin/devel/redmine-test/redmine-5.0.5/plugins/additionals/db/migrate/005_create_dashboard_defaults.rb:5:in `up'
/home/tomin/devel/redmine-test/redmine-5.0.5/bundler/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:870:in `public_send'
/home/tomin/devel/redmine-test/redmine-5.0.5/bundler/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:870:in `exec_migration'
....

```

If I login to redmine as Admin user and use sudo button before trying to migrate it will create dashboard successfully and complete other migrations.

**Comment by HighwayStar** [comment]
Faced this on additionals 3.0.9 and redmine 5.0.5 but other versions should be affected too.

**Comment by HighwayStar** [comment]
Steps to reproduce:

1. Install clean redmine
2. Enable sudo mode
3. Try to login
4. Wait sudo cooldown time 
5. Check in console Admin user changed flag admin: true to admin: false
6. try to add additional plugin and migrate it

**Comment by alexandermeindl** [comment]
Hi @HighwayStar,

I cannot reproduce the error. Do you use any other plugins? (please list it)
It should be always one admin user available in Redmine DB - independent if sudo_mod is active or not active. If no admin user is in your database, you get this error. Can you check your users table in database, if there is an existing admin user in it?

**Comment by HighwayStar** [comment]
Actually seems I've used invalid steps. I've tried to migrate additionals to version 0 and back to current, but redmine_sudo depends on additionals and seems needed to migrate to version 0 in this case too.

I've tried it with many plugins installed to check some conflicts with additionals,  but verified with only redmine_sudo and additionals .

**Comment by alexandermeindl** [comment]
Hi @HighwayStar,

the admin user is created by Redmine core migration `001_setup`, which runs during `db:migrate` - before plugin migrations (`redmine:plugins:migrate`). So in a normal install an active admin exists when this migration runs, and `sudo_mode` doesn't affect it (it's request/session level and doesn't change the DB admin flag; migrations run outside any request). That's why it couldn't be reproduced.

The crash only happens when there's genuinely no active admin at migration time. We've hardened the migration to fail with a clear, actionable message (and the `DEFAULT_USER_ID` hint) instead of the cryptic `NoMethodError`. In the main branch, in stable with the next release. Closing.
