### ISSUE TITLE
When editing and saving a dashboard in a project, the following error occurs.

### ISSUE THREAD

**Issue by jaebokoh** [alphanodes/additionals#191]
Environment:
  Redmine version                5.1.3.stable
  Ruby version                   3.1.6-p260 (2024-05-29) [arm64-darwin23]
  Rails version                  6.1.7.8
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Purplemine2-2.16.2 (includes JavaScript)
SCM:
  Subversion                     1.14.4
  Git                            2.38.0
  Filesystem                     
Redmine plugins:
  additionals                    3.3.2

F, [2024-12-13T12:25:54.085668 #72076] FATAL -- : [7574ca71-2030-44bb-9d4c-4abe9d52a4e7]   
[7574ca71-2030-44bb-9d4c-4abe9d52a4e7] Dashboard::ProjectSystemDefaultChangeException (Dashboard::ProjectSystemDefaultChangeException):
[7574ca71-2030-44bb-9d4c-4abe9d52a4e7]   
[7574ca71-2030-44bb-9d4c-4abe9d52a4e7] plugins/additionals/app/models/dashboard.rb:386:in `validate_project_system_default'
[7574ca71-2030-44bb-9d4c-4abe9d52a4e7] plugins/additionals/app/controllers/dashboards_controller.rb:112:in `update'
[7574ca71-2030-44bb-9d4c-4abe9d52a4e7] lib/redmine/sudo_mode.rb:61:in `sudo_mode'

**Comment by alexandermeindl** [comment]
Hi @jaebokoh,

I cannot reproduce the error. Did you run database migration? Do you use other plugins? Fix yes, can your try without these plugins?

**Comment by alexandermeindl** [comment]
Hi @jaebokoh,

I suppose it was the bug, which I fixed with https://github.com/alphanodes/additionals/commit/5fe2367b0ad4f8290712e14f0179d9be35e38941
This bug only occurred if exactly one project exist in Redmine.

I close this issue for now. If you still have problems with it, please reopen it.
