### ISSUE TITLE
[BUG] NoMethodError: undefined method `alias_method_chain'

### ISSUE THREAD

**Issue by vgavro** [AlphaNodes/additionals#20]
```
Redmine: master 
commit 8117d481ac6582ac1cb51f895b18aa69fa040dda
Date:   Sun Feb 18 05:05:50 2018 +0000
Rails: 5.1.5 (same error with 5.1.4)
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
```
Traceback:
```
redmine@support ~/redmine> bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
NoMethodError: undefined method `alias_method_chain' for #<Class:0x00555bf8772528>
Did you mean?  alias_method
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.5/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
/home/redmine/redmine/plugins/additionals/lib/additionals/patches/issue_patch.rb:7:in `block in included'
/home/redmine/redmine/plugins/additionals/lib/additionals/patches/issue_patch.rb:6:in `class_eval'
/home/redmine/redmine/plugins/additionals/lib/additionals/patches/issue_patch.rb:6:in `included'
/home/redmine/redmine/plugins/additionals/lib/additionals.rb:33:in `include'
/home/redmine/redmine/plugins/additionals/lib/additionals.rb:33:in `block in patch'
/home/redmine/redmine/plugins/additionals/lib/additionals.rb:26:in `each'
/home/redmine/redmine/plugins/additionals/lib/additionals.rb:26:in `patch'
/home/redmine/redmine/plugins/additionals/lib/additionals.rb:57:in `block in <top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:413:in `instance_exec'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:413:in `block in make_lambda'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:600:in `catch'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:600:in `block in default_terminator'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:198:in `block in halting'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:507:in `block in invoke_before'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:507:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:507:in `invoke_before'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:130:in `run_callbacks'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.5/lib/active_support/reloader.rb:87:in `prepare!'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-5.1.5/lib/rails/application/finisher.rb:61:in `block in <module:Finisher>'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-5.1.5/lib/rails/initializable.rb:30:in `instance_exec'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-5.1.5/lib/rails/initializable.rb:30:in `run'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-5.1.5/lib/rails/initializable.rb:59:in `block in run_initializers'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-5.1.5/lib/rails/initializable.rb:58:in `run_initializers'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-5.1.5/lib/rails/application.rb:353:in `initialize!'
/home/redmine/redmine/config/environment.rb:14:in `<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-5.1.5/lib/rails/application.rb:329:in `require_environment!'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-5.1.5/lib/rails/application.rb:445:in `block in run_tasks_blocks'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by alexandermeindl** [comment]
Redmine Additionals does only support Redmine 3.4.x. You try to use it with Redmine trunk, which will not work.
We'll support it, if Redmine 4 has been released. The problem is, if we drop alias_method_chain, all other plugins you use, have also drop alias_method_chain. For now, Redmine 3.4.x is stable and Redmine additionals should work together with other plugins.

**Comment by vgavro** [comment]
Yes, I understand it, just thought you want to support redmine master and last stable at same time. Thanks for reply, of course I switched to stable to use your awesome plugin.
