### ISSUE TITLE
"rake db:create" failed

### ISSUE THREAD

**Issue by sanak** [AlphaNodes/additionals#40]
I tried Redmine 4.0.2 + additionals plugin, but when I executed `bundle exec rake db:create`,
I got the following error.

```
$ bundle exec rake db:create
rake aborted!
ActiveRecord::NoDatabaseError: FATAL:  database "gtt4_dev" does not exist
/Users/sanak/Projects/gtt/git/redmine4/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:696:in `rescue in connect'
/Users/sanak/Projects/gtt/git/redmine4/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:691:in `connect'
/Users/sanak/Projects/gtt/git/redmine4/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:223:in `initialize'
/Users/sanak/Projects/gtt/git/redmine4/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `new'
/Users/sanak/Projects/gtt/git/redmine4/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `postgresql_connection'
/Users/sanak/Projects/gtt/git/redmine4/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:811:in `new_connection'
/Users/sanak/Projects/gtt/git/redmine4/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:855:in `checkout_new_connection'
/Users/sanak/Projects/gtt/git/redmine4/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:834:in `try_to_checkout_new_connection'
/Users/sanak/Projects/gtt/git/redmine4/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:795:in `acquire_connection'
/Users/sanak/Projects/gtt/git/redmine4/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:523:in `checkout'
/Users/sanak/Projects/gtt/git/redmine4/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
/Users/sanak/Projects/gtt/git/redmine4/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:1010:in `retrieve_connection'
/Users/sanak/Projects/gtt/git/redmine4/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/Users/sanak/Projects/gtt/git/redmine4/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2/lib/active_record/connection_handling.rb:90:in `connection'
/Users/sanak/Projects/gtt/git/redmine4/plugins/additionals/init.rb:41:in `<top (required)>'
```

When I commented out the following lines on `init.rb`, then I could create db.
```diff
diff --git a/init.rb b/init.rb
index 9265f4b..eeba4f6 100644
--- a/init.rb
+++ b/init.rb
@@ -38,19 +38,19 @@ Redmine::Plugin.register :additionals do
   RedCloth3::ALLOWED_TAGS << 'div'
 end
 
-if ActiveRecord::Base.connection.table_exists?(:settings)
-  Rails.configuration.to_prepare do
-    Additionals.setup
-  end
-
-  Rails.application.config.after_initialize do
-    FONTAWESOME_ICONS = { fab: AdditionalsFontAwesome.load_icons(:fab),
-                          far: AdditionalsFontAwesome.load_icons(:far),
-                          fas: AdditionalsFontAwesome.load_icons(:fas) }.freeze
-  end
-
-  Rails.application.paths['app/overrides'] ||= []
-  Dir.glob(Rails.root.join('plugins', '*', 'app', 'overrides')).each do |dir|
-    Rails.application.paths['app/overrides'] << dir unless Rails.application.paths['app/overrides'].include?(dir)
-  end
-end
+# if ActiveRecord::Base.connection.table_exists?(:settings)
+#   Rails.configuration.to_prepare do
+#     Additionals.setup
+#   end
+
+#   Rails.application.config.after_initialize do
+#     FONTAWESOME_ICONS = { fab: AdditionalsFontAwesome.load_icons(:fab),
+#                           far: AdditionalsFontAwesome.load_icons(:far),
+#                           fas: AdditionalsFontAwesome.load_icons(:fas) }.freeze
+#   end
+
+#   Rails.application.paths['app/overrides'] ||= []
+#   Dir.glob(Rails.root.join('plugins', '*', 'app', 'overrides')).each do |dir|
+#     Rails.application.paths['app/overrides'] << dir unless Rails.application.paths['app/overrides'].include?(dir)
+#   end
+# end
```

**Comment by alexandermeindl** [comment]
Did you use installation instruction https://github.com/AlphaNodes/additionals#installation. It looks like you did not set RAILS_ENV

**Comment by sanak** [comment]
The following returns same error.
```
bundle exec rails db:create RAILS_ENV=test
bundle exec rails db:create RAILS_ENV=development
```

In your environment, does the following work without problem ?
```
bundle exec rails db:drop
bundle exec rails db:create
```

Note that I am using PostgreSQL environment.

**Comment by alexandermeindl** [comment]
Did you try bundle exec rake db:create RAILS_ENV=production. There should be no problem with the plugin. You need to run db migration, you cannot skip it, if you want to use this plugin. See https://travis-ci.org/AlphaNodes/additionals - installation should run smootly

**Comment by sanak** [comment]
I tried the following, but same error occurred.
```
bundle exec rake db:create RAILS_ENV=production
```

In your travis definition, you use psql command to create database, so it is different approach.
https://github.com/AlphaNodes/additionals/blob/master/.travis.yml#L38
```
- if [[ "$DB" == "postgresql" ]]; then psql -c 'create database travis_ci_test;' -U postgres; fi
```

**Comment by alexandermeindl** [comment]
What is your approach with db:create? This creates a database for Redmine itself. Is this what you want? This plugin requires, that Redmine already is configured and you should use _rake redmine:plugins:migrate_, as described in installation instruction.

**Comment by sanak** [comment]
Yes, `bundle exec rake db:create` is for creating database from `config/database.yml` definition.
(Before I noticed that way, I also used `createdb -U postgres xxx` to create database, then execute `bundle exec rake db:migrate` and `bundle exec rake redmine:plugin:migrate`)

Redmine official plugin tutorial mentions it on `Running test` section, and I feel that this is convenient than manual database creation on test environment, so I hope that this additional plugin support (don't prevent) `rake db:create`. :-)
http://www.redmine.org/projects/redmine/wiki/Plugin_Tutorial#Running-test
```
$ rake db:drop db:create db:migrate redmine:plugins:migrate redmine:load_default_data RAILS_ENV=test
```

**Comment by alexandermeindl** [comment]
I don't know, how I can help you. Please install Redmine first, than run installation instruction to this plugin and it'll work.

**Comment by sanak** [comment]
Well, my explanation might be bad, but I installed Redmine already, and other 18 plugins work well without problem...

Anyway, I will try to fix this issue.
(I think that just fixing the following line will be enough.)
https://github.com/AlphaNodes/additionals/blob/master/init.rb#L41
```
if ActiveRecord::Base.connection.table_exists?(:settings)
```

**Comment by alexandermeindl** [comment]
I updated git master to support single line rake commands and updated travis for it: https://travis-ci.org/AlphaNodes/additionals/jobs/505638339

Let me now, if this works for you.

**Comment by sanak** [comment]
@alexandermeindl 
Okay, I will check it.
Thanks!

**Comment by sanak** [comment]
@alexandermeindl 
I confirmed that master branch with Redmine 4.0.2 + PostgreSQL 11.2 test/development/production environments worked correctly.
Thanks!
