### ISSUE TITLE
Sort is broken on My page

### ISSUE THREAD

**Issue by pbystrov** [AlphaNodes/additionals#43]
I'm unable to sort any issues displayed on My page.
Please find related info below:

```
Started POST "/my?settings%5Bissuesassignedtome%5D%5Bsort%5D=project%3Adesc%2Cpriority%3Adesc%2Cupdated_on%3Adesc" for 127.0.0.1 at 2019-03-15 02:16:13 -0700

ActionController::RoutingError (No route matches [POST] "/my"):

actionpack (5.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.6) lib/rack/method_override.rb:22:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.6) lib/rack/content_length.rb:15:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.2.2) lib/rails/engine.rb:524:in `call'
rack (2.0.6) lib/rack/handler/webrick.rb:86:in `service'
/usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

```
Environment:
  Redmine version                4.0.0.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  5.2.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  additionals                    2.0.19
  clipboard_image_paste          1.13
  redmine_agile                  1.4.8
  redmine_checklists             3.1.14
  redmine_favorite_projects      2.0.3
  redmine_percent_done           1.1.0
  redmine_theme_changer          0.4.0
  redmineup_tags                 2.0.4
```

**Comment by alexandermeindl** [comment]
Hi pbystrov, thanks for reporting this! I fixed it with my last commit, it should work with master branch now.

**Comment by pbystrov** [comment]
Confirmed working, thank you!
