### ISSUE TITLE
Error when installing with redmine 4.0.5

### ISSUE THREAD

**Issue by AizeLeOuf** [AlphaNodes/additionals#58]
Hi,

Here my issue with redmine 4.0.5 and ruby 2.6.0 on master and stable_v2 still the same:

```
redmine_1     | Bundle complete! 54 Gemfile dependencies, 99 gems now installed.
redmine_1     | Gems in the groups development and test were not installed.
redmine_1     | Bundled gems are installed into `/usr/local/bundle`
redmine_1     | rake aborted!
redmine_1     | LoadError: cannot load such file -- ap
redmine_1     | /usr/src/redmine/config/application.rb:5:in `<top (required)>'
redmine_1     | /usr/src/redmine/Rakefile:5:in `<top (required)>'
redmine_1     | /usr/local/bundle/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
redmine_1     | (See full trace by running task with --trace)
redmine_1     | rake aborted!
redmine_1     | LoadError: cannot load such file -- ap
redmine_1     | /usr/src/redmine/config/application.rb:5:in `<top (required)>'
redmine_1     | /usr/src/redmine/Rakefile:5:in `<top (required)>'
redmine_1     | /usr/local/bundle/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
redmine_1     | (See full trace by running task with --trace)
redmine_1     | /usr/local/lib/ruby/2.6.0/bundler/runtime.rb:81:in `require': cannot load such file -- ap (LoadError)
redmine_1     | 	from /usr/local/lib/ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require'
redmine_1     | 	from /usr/local/lib/ruby/2.6.0/bundler/runtime.rb:76:in `each'
redmine_1     | 	from /usr/local/lib/ruby/2.6.0/bundler/runtime.rb:76:in `block in require'
redmine_1     | 	from /usr/local/lib/ruby/2.6.0/bundler/runtime.rb:65:in `each'
redmine_1     | 	from /usr/local/lib/ruby/2.6.0/bundler/runtime.rb:65:in `require'
redmine_1     | 	from /usr/local/lib/ruby/2.6.0/bundler.rb:114:in `require'
redmine_1     | 	from /usr/src/redmine/config/application.rb:5:in `<top (required)>'
redmine_1     | 	from /usr/local/bundle/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:145:in `require'
redmine_1     | 	from /usr/local/bundle/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:145:in `block in perform'
redmine_1     | 	from /usr/local/bundle/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:142:in `tap'
redmine_1     | 	from /usr/local/bundle/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:142:in `perform'
redmine_1     | 	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
redmine_1     | 	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
redmine_1     | 	from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
redmine_1     | 	from /usr/local/bundle/gems/railties-5.2.3/lib/rails/command/base.rb:65:in `perform'
redmine_1     | 	from /usr/local/bundle/gems/railties-5.2.3/lib/rails/command.rb:46:in `invoke'
redmine_1     | 	from /usr/local/bundle/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<top (required)>'
redmine_1     | 	from bin/rails:4:in `require'
redmine_1     | 	from bin/rails:4:in `<main>'
```

my Gemfile.local:

```
gem 'deface', '1.3.2'
gem 'gemoji', '~> 3.0.0'
gem 'invisible_captcha'
gem 'slim-rails'

group :development, :test do
  gem 'brakeman', require: false
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  # TODO: enable rubocop-rails, which requires Redmine 4 only (because of rack 2)
  gem 'rubocop-rails', require: false
end

group :development do
  gem 'awesome_print', require: 'ap' # https://github.com/awesome-print/awesome_print
  gem 'better_errors' # https://github.com/BetterErrors/better_errors
  gem 'binding_of_caller' # better output of with variables for better_errors
end
```

**Comment by AizeLeOuf** [comment]
Ok found add gem 'awesome_print', require: 'ap' # https://github.com/awesome-print/awesome_print
also after gem 'slim-rails'

**Comment by alexandermeindl** [comment]
Ok, I'm glad you find a solution. Not sure, why you use a Gemfile.local for that, but you'll have your reasons ;)

**Comment by ecedi-ld** [comment]
There is still an issue here. gem 'awesome_print', require: 'ap' # https://github.com/awesome-print/awesome_print is mandatory not only for development env put also for production.

**Comment by AizeLeOuf** [comment]
There is still an issue here. gem 'awesome_print', require: 'ap' # https://github.com/awesome-print/awesome_print is mandatory not only for development env put also for production.

**Comment by alexandermeindl** [comment]
If you use the installation instruction of the plugin, bundler does not install gems from test or development group in https://github.com/AlphaNodes/additionals/blob/master/Gemfile

See bundle documentation for that: https://bundler.io/v2.0/man/bundle-install.1.html

**Comment by AizeLeOuf** [comment]
I agree with u. But again if you install your plugin with Redmine 4.0.5 as describe in your readme.MD it doesn't work. Try it !

You need to add line 5 of your Gemfile:

`gem 'awesome_print', require: 'ap' # https://github.com/awesome-print/awesome_print`

**Comment by alexandermeindl** [comment]
We use it with lot of redmine installation with the Gemfile. I think your bundler configuration does not exclude development gems.

Normally you find the used bundle configuration in director ./bundle/config. Here is an example:

```
cat .bundle/config
---
BUNDLE_WITHOUT: "development:test:sqlite:xapian"
```

The gem awesome_print is definitely not required to run additional plugin in production mode.

**Comment by alexandermeindl** [comment]
See installed gems on travis, there is no _awesome_print_ installed. RAILS_ENV test and production does not require this gem as specified in https://github.com/AlphaNodes/additionals/blob/master/Gemfile

**Comment by alexandermeindl** [comment]
Could you solve the problem in the meantime?

**Comment by alexandermeindl** [comment]
Because no further feedback, I close this issue.
