### ISSUE TITLE
Redmine 4.1.0 Compatibility

### ISSUE THREAD

**Issue by dktcoding** [AlphaNodes/additionals#68]
Redmine 4.1.0 added `rubocop` as a dependency: [Add Rubocop to enforce some styles](http://www.redmine.org/issues/31509) and this causes some problems with this amazing plugin.

**Comment by dktcoding** [comment]
Adding some debug info:

~~~
redmine@vps ~/redmine $ bundle install --without development test

[!] There was an error parsing `Gemfile`:
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: rubocop (~> 0.76.0) and rubocop (>= 0). Bundler cannot continue.

 #  from /home/redmine/redmine-4.1.0/plugins/additionals/Gemfile:8
 #  -------------------------------------------
 #    gem 'brakeman', require: false
 >    gem 'rubocop', require: false
 #    gem 'rubocop-performance', require: false
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /home/redmine/redmine-4.1.0/Gemfile:99
 #  -------------------------------------------
 #  Dir.glob File.expand_path("../plugins/*/{Gemfile,PluginGemfile}", __FILE__) do |file|
 >    eval_gemfile file
 #  end
 #  -------------------------------------------
~~~
~~~
redmine@vps ~/redmine $ bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
NoMethodError: undefined method `assets' for #<Rails::Application::Configuration:0x0000564fc722ef58>
Did you mean?  asset_host
/var/lib/gems/2.5.0/gems/railties-5.2.4.1/lib/rails/railtie/configuration.rb:97:in `method_missing'
/home/redmine/redmine-4.1.0/plugins/additionals/lib/additionals.rb:29:in `setup'
/home/redmine/redmine-4.1.0/plugins/additionals/init.rb:46:in `block in <top (required)>'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:426:in `instance_exec'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:605:in `catch'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:199:in `block in halting'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:513:in `each'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:513:in `invoke_before'
gem 'deface', '1.3.2'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:131:in `run_callbacks'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/reloader.rb:89:in `prepare!'
/var/lib/gems/2.5.0/gems/railties-5.2.4.1/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
/var/lib/gems/2.5.0/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `instance_exec'
/var/lib/gems/2.5.0/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `run'
/var/lib/gems/2.5.0/gems/railties-5.2.4.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/var/lib/gems/2.5.0/gems/railties-5.2.4.1/lib/rails/initializable.rb:60:in `run_initializers'
/var/lib/gems/2.5.0/gems/railties-5.2.4.1/lib/rails/application.rb:361:in `initialize!'
/home/redmine/redmine-4.1.0/config/environment.rb:16:in `<top (required)>'
/var/lib/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.5.0/gems/railties-5.2.4.1/lib/rails/application.rb:337:in `require_environment!'
/var/lib/gems/2.5.0/gems/railties-5.2.4.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/var/lib/gems/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
~~~

**Comment by alexandermeindl** [comment]
Thanks for reporting this! For now additionals does not support 4.1. We working on it.

**Comment by alexandermeindl** [comment]
Master branch should work with Redmine 4.1.0 or later.

**Comment by dktcoding** [comment]
I will test it later today!

**Comment by dktcoding** [comment]
Ok, couldn't wait... and...

It's working! Amazing work @alexandermeindl !

~~~
Environment:
  Redmine version                4.1.0.stable
  Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux-gnu]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Bazaar                         2.8.0
  Git                            2.17.1
  Filesystem                     
Redmine plugins:
  additionals                    2.0.23-master
  redmine_callout_macro          1.0.0
  redmine_drawio                 0.8.3
  redmine_issue_templates        0.3.7
  redmine_mermaid_macro          1.0.0
  redmine_tags                   4.0.0
  redmine_zxcvbn                 1.0.0
~~~

**Comment by MasyGreen** [comment]
Great work! Now all its OK.. 4.1

**Comment by RithyKhin** [comment]
Hello @alexandermeindl 

I got another error while I run bellow command, I'm not sure "github/markup" directory get from...

```
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
LoadError: cannot load such file -- github/markup
```

```
Environment:
  Redmine version                4.1.0.stable
  Ruby version                   2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
  Environment                    production
  Database adapter               Mysql2
  Mailer delivery                smtp
SCM:
  Git                            2.17.1
Redmine plugins:
  additionals                    master rev 87fe911
  redmine_git_hosting          4.0.0
```

**Comment by alexandermeindl** [comment]
Hi @RithyKhin 

This does not look that this comes from additionals. Please try additionals without redmine_git_hosting plugin to see, if this works. If this works, you probably should open a issue in redmine_git_hosting  project.

**Comment by RithyKhin** [comment]
Ok, thank for your feedback.

**Comment by alexandermeindl** [comment]
Because no problems are known with Redmine 4.1 at the moment, I close this issue.
