### ISSUE TITLE
Compatibility with plugin "Usability"

### ISSUE THREAD

**Issue by tsnork** [AlphaNodes/additionals#71]
Hi,

there's an issue when both of these plugins are installed:

`Error log
        /opt/redmine/app/helpers/application_helper.rb:1591:in `wiki_helper'
/home/redmine/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/forwardable.rb:222:in `heads_for_wiki_formatter'
/opt/redmine/plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:10:in `heads_for_wiki_formatter'
/opt/redmine/plugins/usability/lib/usability/textile_helper_patch.rb:31:in `heads_for_wiki_formatter_with_us'
/opt/redmine/plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:10:in `heads_for_wiki_formatter'
/opt/redmine/plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:10:in `heads_for_wiki_formatter'
/opt/redmine/plugins/usability/lib/usability/textile_helper_patch.rb:31:in `heads_for_wiki_formatter_with_us'
/opt/redmine/plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:10:in `heads_for_wiki_formatter'
/opt/redmine/plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:10:in `heads_for_wiki_formatter'
/opt/redmine/plugins/usability/lib/usability/textile_helper_patch.rb:31:in `heads_for_wiki_formatter_with_us'
/opt/redmine/plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:10:in `heads_for_wiki_formatter'
/opt/redmine/plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:10:in `heads_for_wiki_formatter'
/opt/redmine/plugins/usability/lib/usability/textile_helper_patch.rb:31:in `heads_for_wiki_formatter_with_us'
...`

which leads to a "Stack level too deep"-Exception in Passenger:

`/home/redmine/.rvm/gems/ruby-2.4.0/gems/passenger-6.0.4/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/home/redmine/.rvm/gems/ruby-2.4.0/gems/passenger-6.0.4/src/ruby_supportlib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
/home/redmine/.rvm/gems/ruby-2.4.0/gems/passenger-6.0.4/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'`

Commenting out one of the functions 'heads_for_wiki_formatter' or 'heads_for_wiki_formatter_with_us' in the ruby source mitigates the issue as a temporary workaround.

**Plugin-Versions used:**

Additionals: 2.0.23
Usability: 2.4.1
Redmine: 4.0.6

Regards,

Dirk

**Comment by alexandermeindl** [comment]
In additionals we switched to the preferred way of overwriting functionality with pretend and "super". Most plugins for Redmine 4 works with it (migrated to it from "alias_method"). 

Because of this, we cannot fix your problem in additionals plugin. Please contact Usability developers to fix this problem.

**Comment by tsnork** [comment]
Thanks for your feedback, I'll try & contact the Usability guys!

**Comment by jwalkerbg** [comment]
My installation have installed these plugins:

issue_reccuring
redmine_code_preview
redmine_issue_templates
redmine_latex_mathjax
redmine_theme_changer

**Comment by alexandermeindl** [comment]
Hi @tsnork,

this is the known incompatibility between alias-based method wrapping (used by the usability plugin, via `alias_method_chain`/`alias_method`) and `prepend`/`super` (additionals) on the same wiki-formatter method - mixing the two on one method causes the infinite recursion. The fix is for the usability plugin to override via `prepend`/`super` instead; then both compose cleanly. additionals is already on that approach. Closing - the versions here are also long EOL.
