### ISSUE TITLE
Recursion Crash when going to settings page, news page and documents page

### ISSUE THREAD

**Issue by TQING1990** [AlphaNodes/additionals#76]
I use docker redmine:4

when I go to administration -> settings, projects-> settings, news page and documents page. I get a recursive issue:

plugins/redmine_quick_replies/lib/redmine_quick_replies/patches/wiki_formatting_patch.rb:17:in `heads_for_wiki_formatter_with_redmine_quick_replies'
plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:10:in `heads_for_wiki_formatter'
plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:10:in `heads_for_wiki_formatter'
plugins/redmine_quick_replies/lib/redmine_quick_replies/patches/wiki_formatting_patch.rb:17:in `heads_for_wiki_formatter_with_redmine_quick_replies'
plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:10:in `heads_for_wiki_formatter'
...
...
...

I think it conflicts with redmine_quick_replies plus

**Comment by alexandermeindl** [comment]
Hi @TQING1990,

same as here https://github.com/AlphaNodes/additionals/issues/71#issuecomment-591290491

This cannot be fixed, because a plugin can only be use prepend or alias_method. More plugins use prepend - and is more modern - of these reasons additionals plugins use prepend.

**Comment by TQING1990** [comment]
thanks

**Comment by alexandermeindl** [comment]
Hi @tqing1128,

same root cause as #71: redmine_quick_replies overrides `heads_for_wiki_formatter` via alias-based wrapping, which is incompatible with additionals' `prepend`/`super` on the same method, causing the recursion. The fix is for that plugin to switch to `prepend`/`super`. Closing as a duplicate of #71 (and the versions here are long EOL).
